id: P4532133F
initial_creation_type: input
source_metadata:
  title: Āryaśūra Series
  language: es
  description: Texts by the great Indian master Āryaśūra, known to Tibetans as Lobpon
    Pawo (slob dpon dpa' bo), author of the famous Garland of Birth Stories (Jātakamālā)
  volume:
    8b4ca13197374ae9917550b8358ee283:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    b5eb01e0f23f45859f2b5ee781e77a93:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T02:08:51.634677'
last_modified_at: '2022-03-01T02:08:51.634679'
